sudo: false
language: ruby
cache: bundler
rvm:
- 2.5
- 2.6
- ruby-head
matrix:
  fast_finish: true
  allow_failures:
  - rvm: ruby-head
before_install:
- gem update --system
- gem install bundler
install:
- bundle install --jobs=3 --retry=3
script:
- bundle exec rspec
- bundle exec rubocop
- bundle exec fasterer
notifications:
  email: false
  slack:
    secure: pZ+VjpEsHwWJ7rxfcCX6UVr+8m5fxeJnRBCRJa4cR9QNYcCN4FUDd6HzZ7t/tSY+VgtuTqOKPN5szA0T5Ldvnh7gbNPnuX94KJN2nxBPcj5vzmJbt/V/XSn2DKZ86m3S/2bixbaNS0U2yOWTZMJIwGD2+nmz0uNS7885hMlm/Aa8U5JqYuktFYwo383iOvh+nUZLw8lPl59j4o+lo4LP+QHOJDj3gytPVo4TC3OSa5fqUa/HZbSSYWdoy/1pkAP0kqF3AbgEU/lPHbWGH7Kf1aJaWTJ3oGLrMzLWDjy1NCawFU65FfCMa6cF3AYCdNX5YFQjvonBblDXOfwopqthcXohZtQ1R8FACfHPG63eSCprQvb1TFqd+0nbzRZlXZNvikfLVtRvnUZGBmxTpbB8DfnPEnw6NA4s5A0iW4fJ+qRP3t7qUOGo3EzUsBTyRo+ZlZQ52h286E5vkbNmH9lcJDnCw2wicWHjQPMuya6FjD0gC7CO0W3+loi0S/ODU51MIKs3/0Iww9OUs27651fDu9wrUKq4AEoDM8ZT2cNsa+zKTzNH8JB+Ptz+ciZDZfEnrp0+Pe+ahiO/VS6NUBwGHlvqDVpiQXcFHfenAA5nK22F78qm5CGu+JjwuuDRcLwVfo0etmT3libSj3p9J6KBVvbndvGAsx+Juu0B+pitJyw=
